[package]
name = "topgrade"
description = "Upgrade all the things"
categories = ["os"]
keywords = ["upgrade", "update"]
license-file = "LICENSE"
repository = "https://github.com/topgrade-rs/topgrade"
version = "10.1.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>", "Thomas Schönauer <t.schoenauer@hgs-wt.at>"]
exclude = ["doc/screenshot.gif"]
edition = "2021"

readme = "README.md"

[[bin]]
name = "topgrade"
path = "src/main.rs"
##[lib]
##name = "topgrade_lib"

[dependencies]
anyhow = "1.0"
cfg-if = "1.0"
chrono = "0.4"
clap = { version = "3.1", features = ["cargo", "derive"] }
console = "0.15"
directories = "4.0"
futures = "0.3"
glob = "0.3"
home = "0.5"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.6"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "2.1"
strum = { version = "0.24", features = ["derive"] }
sys-info = "0.9"
tempfile = "3.3"
thiserror = "1.0"
tokio = { version = "1.21", features = ["process", "rt-multi-thread"] }
toml = "0.5"
walkdir = "2.3"
which_crate = { version = "4.3", package = "which" }

[target.'cfg(target_os = "macos")'.dependencies]
notify-rust = "4.5"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"
rust-ini = "0.18"
self_update_crate = { version = "0.32", default-features = false, optional = true, package = "self_update", features = ["archive-tar", "compression-flate2", "rustls"] }

[target.'cfg(windows)'.dependencies]
self_update_crate = { version = "0.32", default-features = false, optional = true, package = "self_update", features = ["archive-zip", "compression-zip-deflate", "rustls"] }
winapi = "0.3"
parselnk = "0.1"

[profile.release]
lto = true

[features]
default = []
self-update = ["self_update_crate"]
